### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by sweeneyb** [alphagov/terraform-provider-concourse#1]
This project doesn't have a license.  I'd like to reuse/help, but I can't unless it's licensed in a corporate friendly way (BSD, apache 2.0, MIT, etc).  Would it be possible to add a license? 

Thanks!

**Comment by tlwr** [comment]
Thanks for this issue, I have added the standard Crown Copyright license

**Comment by sweeneyb** [comment]
Very much appreciated!
