### ISSUE TITLE
Publish provider

### ISSUE THREAD

**Issue by allandegnan** [alphagov/terraform-provider-concourse#12]
Hi!

First of all, thanks for the provider.  Using it and it works a treat.  It'd be nice, especially for local users, if it didn't require manually building and discovering.  There's some docs about setting up this officially and terraform .13 will support 3rd party providers better.

https://www.terraform.io/docs/registry/providers/publishing.html

Are you open to this?  Obviously I can PR an action to build and release, but I can't be providing registry accounts and signing keys.

**Comment by tlwr** [comment]
I think it is also in the interests of @alphagov if we distributed this properly, because we also have to deal with building and discovery.

We have prior art to automate distribution via GitHub releases, although we'll have to figure how to fit GPG signing into this release process

**Comment by OldBlackJoe** [comment]
I want this too!

**Comment by risicle** [comment]
https://registry.terraform.io/providers/terraform-provider-concourse/concourse
