### ISSUE TITLE
Running with terraform 0.13?

### ISSUE THREAD

**Issue by vkrot-exos** [alphagov/terraform-provider-concourse#14]
Hi all,
First of all thanks for the project!
How can I run it with terraform 0.13?
I did `make install` and add provider to my `config.tf`, but `terraform init` produces error:
```
Error: Failed to install provider

Error while installing hashicorp/concourse: provider registry
[registry.terraform.io](http://registry.terraform.io/) does not have a provider named
[registry.terraform.io/hashicorp/concourse](http://registry.terraform.io/hashicorp/concourse)
```

I believe I need to add `required_providers.concourse.source`, but what should I write to source?

Thanks in advance

**Comment by risicle** [comment]
See https://registry.terraform.io/providers/terraform-provider-concourse/concourse
